language: ruby
rvm:
- 2.1.5
script: true
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: ShQ2DhljgjwvfxSpbBhHvIO3Br3y++8YbuTbjA+zRO6nRrGmgKukipvqsi8WibjpqBgDws1u4SpNp06Aef8NYTCYgISAh48ZkwvtUM+4wJXqw3ijNXr5oJoEE89rDM5jRp5Aft5BBmx2GA6TS1Fxav61RAC7/zKEsJTSrtYikS4=
  app:
    master: gratipay-access-dashboard
  on:
    repo: gratipay/access-dashboard
    branch: master
